server:
  port: 8081

spring:
  application:
    name: transaction-engine

  # Java 21 Virtual Threads
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/finguard_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# gRPC Configuration
grpc:
  client:
    fraud-service:
      # CRITICAL FIX: Use 127.0.0.1 instead of a hostname
      address: static://127.0.0.1:9090
      negotiation-type: plaintext